pipeline:
  projectIdentifier: tanays
  orgIdentifier: traceablecsindia
  tags: {}
  stages:
    - stage:
        name: DAST
        identifier: DAST
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
            paths: []
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Traceable
                  name: Traceable
                  identifier: Traceable
                  spec:
                    auth:
                      access_token: M2ExNzNhNGItMjlmYi00MThhLWIxOTQtN2JhYTVkMjc0NjA3
                      domain: https://api.apac.traceable.ai
                    mode: orchestration
                    config: default
                    target:
                      type: instance
                      detection: auto
                    advanced:
                      log:
                        level: debug
                    tool:
                      suite_id: eff7ffd6-14d1-4af4-8e95-573cd38d3209
                  when:
                    stageStatus: Success
                    condition: "false"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        when:
          pipelineStatus: All
  allowStageExecutions: true
  identifier: Traceable_DAST_Scan
  name: Traceable DAST Scan
