pipeline:
  name: Demo-pipeline
  identifier: Demopipeline
  projectIdentifier: tanayssto
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: tanays
        repoName: crAPI
        build: <+input>
  stages:
    - stage:
        name: Security-Scans
        identifier: SecurityScans
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_1
                  identifier: Semgrep_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
