pipeline:
  name: Master-STO
  identifier: MasterSTO
  projectIdentifier: tanayssto
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: tanays
        repoName: WebGoat
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Security
        identifier: Security
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Semgrep
                  name: Semgrep_1
                  identifier: Semgrep_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
              - step:
                  type: Owasp
                  name: Owasp_1
                  identifier: Owasp_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
              - step:
                  type: Checkov
                  name: Checkov_1
                  identifier: Checkov_1
                  spec:
                    target:
                      detection: auto
                      type: repository
                    advanced:
                      log:
                        level: info
                      args: {}
                    mode: orchestration
                    config: default
              - step:
                  type: Traceable
                  name: API_DAST_1
                  identifier: API_DAST_1
                  spec:
                    auth:
                      access_token: MTJmZDAxOTAtM2NmOC00NGMxLWE4YWItZjc3NDY3ZTA3MTk1
                      domain: https://api.apac.traceable.ai
                    mode: orchestration
                    config: default
                    target:
                      type: instance
                      detection: auto
                    advanced:
                      log:
                        level: info
                    tool:
                      suite_id: 2dbf201f-01c3-49ad-88d1-a214b793c976
                      runner_id: 04367ea8-17f2-5fc5-b9ad-91a211ab5773
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: tanaysdelegate
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
