pipeline:
  name: GitLeaks
  identifier: Security
  projectIdentifier: tanayssto
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: tanays
        repoName: crAPI
        build: <+input>
  stages:
    - stage:
        name: Security
        identifier: Security
        description: ""
        type: SecurityTests
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Gitleaks
                  name: Gitleaks_1
                  identifier: Gitleaks_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                  enforce:
                    policySets:
                      - tanaytest
              - step:
                  type: Semgrep
                  name: Semgrep_1
                  identifier: Semgrep_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                  enforce:
                    policySets:
                      - tanaytest
  notificationRules:
    - name: test
      identifier: test
      pipelineEvents:
        - type: StageSuccess
          forStages:
            - Security
      notificationMethod:
        type: Email
        spec:
          userGroups: []
          recipients:
            - tanay.sethi@harness.io
      template:
        versionLabel: "1"
        templateRef: TestNotification
      enabled: true
