name: Test Traceable AST Init And Run Action With AST Scan Suite
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  InitAndRunAstScan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init and run scan action
        uses: Traceableai/ast-action@main
        with:
          step_name: 'init and run'
          client_scan_token: N2Y4YTFhMTQtNzM0ZS00MDkyLWEyYjktYmE3OWE4NWI4MGI5
          cli_version: 'latest'
          scan_suite: 'github-actions-test-suite'
          traceable_server: api-dev.traceable.ai
      - name: Stop Scan
        if: always()
        uses: Traceableai/ast-action@main
        with:
          step_name: 'stop'
          client_scan_token: N2Y4YTFhMTQtNzM0ZS00MDkyLWEyYjktYmE3OWE4NWI4MGI5
          traceable_server: api-dev.traceable.ai
  functionalTest:
    runs-on: ubuntu-20.04
    steps:
      - name: Run a loop as functional test (This is sample)
        run: |
          for ((i=1;i<=100;i++)); 
          do 
             echo $i
          done
